title: UAH Notes
description: My course notes and study guides


# This plugin converts [Link](file.md) to <a href="file.html"> automatically
plugins:
  - jekyll-relative-links

# Configure the plugin
relative_links:
  enabled: true
  collections: true

# Apply the theme to all files
defaults:
  - scope:
      path: ""
    values:
      layout: "default"

safe: true
lsi: false
incremental: false
highlighter: rouge
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge